services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - path: .
          action: sync
          target: /api


  mongo:
    image: mongo
    restart: always